services:
  frontend:
    restart: always
    image: lone-social:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
    env_file:
      - .env
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NODE_OPTIONS=--max-old-space-size=4096
