name: Deploy Application

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning a repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Create .env file
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "MOCK_SERVICE_WORKER=${{ secrets.MOCK_SERVICE_WORKER }}" >> .env
          echo "FIREBASE_APIKEY=${{ secrets.FIREBASE_APIKEY }}" >> .env
          echo "FIREBASE_AUTHDOMAIN=${{ secrets.FIREBASE_AUTHDOMAIN }}" >> .env
          echo "FIREBASE_PROJECTID=${{ secrets.FIREBASE_PROJECTID }}" >> .env
          echo "FIREBASE_STORAGEBUCKET=${{ secrets.FIREBASE_STORAGEBUCKET }}" >> .env
          echo "FIREBASE_MESSAGINGSENDERID=${{ secrets.FIREBASE_MESSAGINGSENDERID }}" >> .env
          echo "FIREBASE_APPID=${{ secrets.FIREBASE_APPID }}" >> .env

      - name: Copying files to the server
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PATH }}

      - name: Move .env file to the server
        run: |
          scp -i ~/.ssh/id_rsa .env ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PATH }}/.env

      - name: Build and restart containers
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ${{ secrets.SERVER_PATH }}
            docker compose down
            docker compose up --build -d
          EOF

      - name: Cleanup
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            docker container prune -f &&
            docker image prune -f --filter 'dangling=true'
          "
